language:
  - ruby
rvm:
  - 2.2.3
sudo: false
addons:
  apt:
    sources:
      ubuntu-toolchain-r-test
    packages:
      g++-4.9
env:
  global:
    - RAILS_ENV=test
    - CXX=g++-4.9
install:
  - bundle install
  - nvm install 5.0
  - nvm use 5.0
  - npm install
before_script:
   - export DISPLAY=:99.0
   - sh -e /etc/init.d/xvfb start
script:
  - bundle exec rake db:schema:load
  - DRIVER=selenium_firefox bundle exec rake
  - bundle exec rake lint
