json.extract! task, :id,
                    :title, 
                    :description,
                    :deadline,
                    :pretty_deadline,
                    :category,
                    :status,
                    :is_overdue,
                    :created_at,
                    :updated_at
