json.extract! task, :id,
                    :title,
                    :description,
                    :deadline,
                    :category,
                    :status,
                    :is_overdue,
                    :partner_id,
                    :created_at,
                    :updated_at
